export interface KeyPlayer {
  name: string;
  pos: 'GK' | 'DF' | 'MF' | 'FW';
  note: string;
}

export interface TeamDossier {
  rank: number;
  coach: string;
  nickname: string;
  recent?: string;
  style: string;
  keyPlayers: KeyPlayer[];
  strengths: string[];
  weaknesses: string[];
  outlook: string;
}

export interface H2HRecord {
  w: number;
  d: number;
  l: number;
  gf: number;
  ga: number;
}

export interface H2HEntry {
  comp?: H2HRecord;
  friendly?: H2HRecord;
}

export const TEAM_DOSSIER: Record<string, TeamDossier> = {
  'Mexico': {
    rank: 15, coach: 'Javier Aguirre', nickname: 'El Tri',
    recent: 'WC22: Group stage',
    style: 'Possession-oriented co-hosts who build patiently and lean on home crowds; can lack a clinical edge.',
    keyPlayers: [
      { name: 'Raúl Jiménez', pos: 'FW', note: '3rd all-time Mexico scorer (44); Fulham target man' },
      { name: 'Edson Álvarez', pos: 'MF', note: 'Defensive midfield anchor and captain figure' },
      { name: 'Santiago Giménez', pos: 'FW', note: 'Modern No.9, movement in the box' },
    ],
    strengths: ['Home advantage', 'Tournament experience', 'Strong spine through midfield'],
    weaknesses: ['Decades of round-of-16 ceiling', 'Finishing droughts', 'Pressure of host expectation'],
    outlook: 'Heavy favorites to top Group A; the real test is finally breaking the last-16 curse.',
  },
  'South Africa': {
    rank: 60, coach: 'Hugo Broos', nickname: 'Bafana Bafana',
    style: 'Energetic, youthful side that presses and attacks through the wide areas.',
    keyPlayers: [
      { name: 'Oswin Appollis', pos: 'FW', note: 'Qualifying talisman — 2 goals, 4 assists' },
      { name: 'Lyle Foster', pos: 'FW', note: 'Burnley striker, pace in behind' },
      { name: 'Ronwen Williams', pos: 'GK', note: 'Captain and shot-stopper' },
    ],
    strengths: ['Pace out wide', 'Veteran coach who wins tournaments', 'No pressure underdogs'],
    weaknesses: ['Thin elite experience', 'Goals can dry up', 'Defensive lapses'],
    outlook: 'Roughly a coin-flip to reach the round of 32; the dark horse of Group A.',
  },
  'South Korea': {
    rank: 25, coach: 'Hong Myung-bo', nickname: 'Taegeuk Warriors',
    recent: 'WC22: Round of 16',
    style: 'High-tempo, hard-running side built on European-based talent and relentless work rate.',
    keyPlayers: [
      { name: 'Son Heung-min', pos: 'FW', note: 'Captain and talisman; pace and finishing' },
      { name: 'Lee Kang-in', pos: 'MF', note: '2025 KOR Footballer of the Year; UCL winner with PSG' },
      { name: 'Kim Min-jae', pos: 'DF', note: 'Bayern centre-back, defensive rock' },
    ],
    strengths: ['World-class attacking duo', 'Stamina and work rate', 'Big-club defenders'],
    weaknesses: ['Over-reliance on Son', 'Can be opened up in transition', 'Squad depth'],
    outlook: 'Second favorites in Group A and a likely qualifier with their star quality.',
  },
  'Czechia': {
    rank: 41, coach: 'Ivan Hašek', nickname: 'Repre',
    recent: 'WC06: Group stage',
    style: 'Organized, physical and a genuine set-piece menace — scored more corners than any European side in qualifying.',
    keyPlayers: [
      { name: 'Patrik Schick', pos: 'FW', note: 'Leverkusen striker; top scorer in qualifying (5)' },
      { name: 'Tomáš Souček', pos: 'MF', note: 'Box-to-box presence, aerial threat' },
      { name: 'Lukáš Provod', pos: 'MF', note: 'Creativity and long-range threat' },
    ],
    strengths: ['Elite set-piece execution (7 corner goals)', 'Physicality', 'A proven goalscorer'],
    weaknesses: ['Can be passive in open play', 'Pace in wide defense', 'Reliant on Schick'],
    outlook: 'Live for second place; their dead-ball threat can decide tight games.',
  },
  'Canada': {
    rank: 30, coach: 'Jesse Marsch', nickname: 'Les Rouges',
    recent: 'WC22: Group stage',
    style: 'Aggressive high press and fast vertical transitions under Jesse Marsch.',
    keyPlayers: [
      { name: 'Alphonso Davies', pos: 'DF', note: 'Bayern flyer; overlapping pace down the left' },
      { name: 'Jonathan David', pos: 'FW', note: 'Elite movement and finishing' },
      { name: 'Stephen Eustáquio', pos: 'MF', note: 'Midfield metronome' },
    ],
    strengths: ['Two genuinely elite players', 'High-energy press', 'Co-host momentum'],
    weaknesses: ["Never won a men's WC game", 'Defensive depth', 'Tournament inexperience'],
    outlook: 'Chasing a first-ever World Cup point and a knockout spot — both within reach.',
  },
  'Bosnia and Herz.': {
    rank: 65, coach: 'Sergej Barbarez', nickname: 'Zmajevi (Dragons)',
    style: 'Pragmatic and structured; resilient, physical and dangerous from set pieces rather than free-flowing.',
    keyPlayers: [
      { name: 'Edin Džeko', pos: 'FW', note: 'Veteran talisman and all-time top scorer' },
      { name: 'Sead Kolašinac', pos: 'DF', note: 'Physical, combative defender' },
      { name: 'Esmir Bajraktarević', pos: 'MF', note: 'Young creative spark' },
    ],
    strengths: ['Knocked out Italy to qualify', 'Set-piece threat', 'Discipline and resilience'],
    weaknesses: ['Aging core', 'Limited control of matches', 'Lacks pace'],
    outlook: 'Tournament returnees who will make every game uncomfortable; outsiders to advance.',
  },
  'Qatar': {
    rank: 55, coach: 'Julen Lopetegui', nickname: 'The Maroon',
    recent: 'WC22: Group stage',
    style: 'Technical, patient possession football — a step up in pragmatism under Lopetegui after a chastening 2022.',
    keyPlayers: [
      { name: 'Almoez Ali', pos: 'FW', note: 'Record goalscorer, 2019 Asian Cup top scorer' },
      { name: 'Akram Afif', pos: 'FW', note: 'Creative winger, two-time Asian Player of the Year' },
      { name: 'Abdulaziz Hatem', pos: 'MF', note: 'Midfield engine' },
    ],
    strengths: ['Experienced coach', 'Settled core from Asian Cup wins', 'Technical quality'],
    weaknesses: ['Winless on WC debut as 2022 hosts', 'Limited size/physicality', 'Untested vs elite'],
    outlook: 'Seeking redemption after 2022; needs a major upset to advance.',
  },
  'Switzerland': {
    rank: 19, coach: 'Murat Yakin', nickname: 'Nati',
    recent: 'WC22: Round of 16',
    style: 'Technically complete, defensively solid tournament side that grinds out results and excels in knockouts.',
    keyPlayers: [
      { name: 'Granit Xhaka', pos: 'MF', note: 'Captain and midfield conductor' },
      { name: 'Manuel Akanji', pos: 'DF', note: 'Composed, ball-playing centre-back' },
      { name: 'Dan Ndoye', pos: 'FW', note: 'Direct wide threat' },
    ],
    strengths: ['Six straight World Cups', 'Knockout pedigree (beat France, Italy, Spain)', 'Defensive structure'],
    weaknesses: ['Lacks a prolific striker', 'Can be too cautious', 'Aging spine'],
    outlook: 'The "big boy" of Group B and clear favorites to top it.',
  },
  'Brazil': {
    rank: 6, coach: 'Carlo Ancelotti', nickname: 'Seleção',
    recent: 'WC22: Quarterfinals',
    style: 'More measured and balanced under Ancelotti than past improvisational sides — better structured defensively, still loaded in attack.',
    keyPlayers: [
      { name: 'Vinícius Júnior', pos: 'FW', note: 'Match-winning dribbler on the left' },
      { name: 'Raphinha', pos: 'FW', note: 'Direct, prolific wide forward' },
      { name: 'Alisson', pos: 'GK', note: 'World-class goalkeeper' },
      { name: 'Marquinhos', pos: 'DF', note: 'Defensive leader' },
    ],
    strengths: ['Deepest attacking pool in the field', 'Elite manager', 'Improved defensive shape'],
    weaknesses: ['Questions over a settled No.9', 'Big-game scar tissue', 'Midfield balance'],
    outlook: 'Group C favorites and genuine title contenders under Ancelotti.',
  },
  'Morocco': {
    rank: 8, coach: 'Mohamed Ouahbi', nickname: 'Atlas Lions',
    style: 'Tactically mature, defensively disciplined and lethal in transition — the blueprint from their 2022 semi-final run.',
    keyPlayers: [
      { name: 'Achraf Hakimi', pos: 'DF', note: 'Elite attacking right-back' },
      { name: 'Brahim Díaz', pos: 'MF', note: 'Creative spark between the lines' },
      { name: 'Bilal El Khannouss', pos: 'MF', note: 'Rising playmaker' },
    ],
    strengths: ['Best-ever African WC finish (4th, 2022)', 'AFCON champions (disputed)', 'Tactical maturity'],
    weaknesses: ['New coach mid-cycle', 'Reliance on transitions', 'Goal threat through the middle'],
    outlook: "Brazil's biggest threat in Group C and a dark horse to go deep again.",
  },
  'Haiti': {
    rank: 83, coach: 'Sébastien Migné', nickname: 'Les Grenadiers',
    style: 'Quick in transition and defensively organized — a spoiler that sits in and counters.',
    keyPlayers: [
      { name: 'Duckens Nazon', pos: 'FW', note: 'All-time top scorer (44); Concacaf qualifying top scorer (6)' },
      { name: 'Frantzdy Pierrot', pos: 'FW', note: 'Physical focal point' },
      { name: 'Johnny Plácide', pos: 'GK', note: 'Experienced last line' },
    ],
    strengths: ['Transition speed', 'Defensive organization', 'Nothing-to-lose freedom'],
    weaknesses: ['Lowest qualifying odds of all 48', 'Limited possession quality', 'Squad depth'],
    outlook: 'First World Cup since 1974; rated the least likely of all 48 to advance.',
  },
  'Scotland': {
    rank: 43, coach: 'Steve Clarke', nickname: 'Tartan Army',
    style: 'Structured, physical and combative — makes every match uncomfortable, strong from set pieces.',
    keyPlayers: [
      { name: 'Scott McTominay', pos: 'MF', note: 'Napoli cult hero; scored a stunning qualifier' },
      { name: 'Andy Robertson', pos: 'DF', note: 'Captain; attacking left-back' },
      { name: 'John McGinn', pos: 'MF', note: 'Aston Villa midfielder; energy and goals' },
    ],
    strengths: ['Physical and organized', 'Set-piece threat', 'Ends a 28-year WC wait fired up'],
    weaknesses: ['Never escaped a WC group', 'Limited cutting edge', 'Depth in attack'],
    outlook: 'First World Cup since 1998; will scrap for a historic knockout place.',
  },
  'USA': {
    rank: 16, coach: 'Mauricio Pochettino', nickname: 'USMNT',
    recent: 'WC22: Round of 16',
    style: 'Athletic, high-pressing co-hosts riding huge home support and a golden generation of Europe-based players.',
    keyPlayers: [
      { name: 'Christian Pulisic', pos: 'FW', note: 'Talisman; thriving at AC Milan' },
      { name: 'Weston McKennie', pos: 'MF', note: 'Energy and goals from midfield' },
      { name: 'Antonee Robinson', pos: 'DF', note: 'Flying overlapping full-back' },
    ],
    strengths: ['Home advantage (two LA group games)', 'European-based core', 'Elite manager'],
    weaknesses: ['Inconsistent results under pressure', 'Center-forward question', 'Big-game nerves'],
    outlook: 'Favorites in an open Group D; a deep run is the national expectation.',
  },
  'Paraguay': {
    rank: 40, coach: 'Gustavo Alfaro', nickname: 'La Albirroja',
    style: 'The most disciplined defensive unit from CONMEBOL — vertical, physical, punishing on the counter.',
    keyPlayers: [
      { name: 'Miguel Almirón', pos: 'MF', note: 'Transition engine; everything runs through him' },
      { name: 'Antonio Sanabria', pos: 'FW', note: 'Experienced focal point' },
      { name: 'Julio Enciso', pos: 'FW', note: 'Spark of individual quality' },
    ],
    strengths: ['Conceded just 10 in 18 qualifiers', 'Counter-attacking threat', 'Defensive discipline'],
    weaknesses: ['Limited creativity in possession', 'Reliance on Almirón', 'Goal threat'],
    outlook: 'Hard to beat and a real shout for a top-two finish in Group D.',
  },
  'Australia': {
    rank: 27, coach: 'Tony Popovic', nickname: 'Socceroos',
    recent: 'WC22: Round of 16',
    style: 'Organized, hard-working and resilient — defends well and grinds out tournament results.',
    keyPlayers: [
      { name: 'Mathew Ryan', pos: 'GK', note: 'Captain; nine clean sheets in LaLiga last season' },
      { name: 'Jackson Irvine', pos: 'MF', note: 'Midfield leader and runner' },
      { name: 'Martin Boyle', pos: 'FW', note: 'Direct wide threat' },
    ],
    strengths: ['Reached R16 in 2022', 'Defensive organization', 'Tournament know-how'],
    weaknesses: ['Limited attacking firepower', 'Aging in key areas', 'Goals hard to come by'],
    outlook: "Won't just make up the numbers; capable of nicking a knockout spot.",
  },
  'Turkey': {
    rank: 26, coach: 'Vincenzo Montella', nickname: 'Crescent-Stars',
    style: 'Talented, attack-minded side full of big-club technicians — dangerous going forward after a 24-year absence.',
    keyPlayers: [
      { name: 'Arda Güler', pos: 'MF', note: 'Real Madrid playmaker; the creative jewel' },
      { name: 'Hakan Çalhanoğlu', pos: 'MF', note: 'Deep-lying conductor and dead-ball ace' },
      { name: 'Kenan Yıldız', pos: 'FW', note: 'Juventus forward, rising star' },
    ],
    strengths: ['Genuine attacking quality', 'Creative midfield', 'High ceiling'],
    weaknesses: ['Defensive reliability', '24 years of WC rust', 'Consistency'],
    outlook: 'Slight co-favorites with the USA to take a top-two spot in Group D.',
  },
  'Germany': {
    rank: 10, coach: 'Julian Nagelsmann', nickname: 'Die Mannschaft',
    recent: 'WC22: Group stage',
    style: 'Possession-based control with aggressive counter-pressing under Nagelsmann; loaded with young creators.',
    keyPlayers: [
      { name: 'Jamal Musiala', pos: 'MF', note: 'Dribbling genius between the lines' },
      { name: 'Florian Wirtz', pos: 'MF', note: 'Elite creator and tempo-setter' },
      { name: 'Joshua Kimmich', pos: 'MF', note: 'Captain and midfield organizer' },
    ],
    strengths: ['World-class young attackers', 'Possession control', 'Quarterfinalists at Euro 2024'],
    weaknesses: ['Defensive fragility at times', 'Settled No.9', 'Recent tournament knockouts'],
    outlook: 'Clear Group E favorites (96% to advance) and dark-horse contenders.',
  },
  'Curaçao': {
    rank: 82, coach: 'Dick Advocaat', nickname: 'Blue Wave',
    style: 'Organized, pragmatic and compact — a defensive block springing forward through Dutch-schooled attackers.',
    keyPlayers: [
      { name: 'Leandro Bacuna', pos: 'MF', note: 'Versatile 34-yr-old captain; 2nd top scorer' },
      { name: 'Tahith Chong', pos: 'FW', note: 'Sheffield United winger, dribbling threat' },
      { name: 'Armando Obispo', pos: 'DF', note: 'PSV-schooled defensive anchor' },
      { name: 'Sontje Hansen', pos: 'FW', note: 'Middlesbrough forward, pace in transition' },
    ],
    strengths: ['Defensive organization', 'Deep pool of Dutch-developed pros', 'Nothing-to-lose freedom'],
    weaknesses: ['Smallest nation ever to qualify', 'No tournament pedigree', 'Managerial turmoil pre-tournament'],
    outlook: "The tournament's great story; a single point would be historic.",
  },
  'Ivory Coast': {
    rank: 34, coach: 'Emerse Faé', nickname: 'Les Éléphants',
    style: '4-3-3 built on a compact midfield block and fast, technically gifted wide attackers.',
    keyPlayers: [
      { name: 'Yan Diomande', pos: 'FW', note: 'Electric 19-yr-old RB Leipzig winger' },
      { name: 'Simon Adingra', pos: 'FW', note: 'Pace and dribbling out wide' },
      { name: 'Franck Kessié', pos: 'MF', note: 'Powerful midfield driver' },
    ],
    strengths: ['Athletic, direct wide play', 'AFCON champion in 2023', 'Young attacking talent'],
    weaknesses: ['Goal threat through the middle', 'Defensive consistency', 'Tournament-football naivety'],
    outlook: 'In a tight fight with Ecuador for second behind Germany.',
  },
  'Ecuador': {
    rank: 23, coach: 'Sebastián Beccacece', nickname: 'La Tri',
    recent: 'WC22: Group stage',
    style: 'High-energy, technically disciplined team that presses hard and defends superbly.',
    keyPlayers: [
      { name: 'Moisés Caicedo', pos: 'MF', note: 'Chelsea engine; elite ball-winner' },
      { name: 'Willian Pacho', pos: 'DF', note: 'PSG centre-back, defensive rock' },
      { name: 'Piero Hincapié', pos: 'DF', note: 'Composed, aggressive defender' },
    ],
    strengths: ['Outstanding defensive core', 'Midfield steel in Caicedo', 'Conceded fewest in qualifying'],
    weaknesses: ['Goalscoring depth', 'Reliance on young spine', 'Final-third creativity'],
    outlook: 'Favored for second in Group E; a stingy defense makes them dangerous.',
  },
  'Netherlands': {
    rank: 7, coach: 'Ronald Koeman', nickname: 'Oranje',
    recent: 'WC22: Quarterfinals',
    style: 'Technically excellent and experienced, built on a strong defense and midfield control rather than firepower.',
    keyPlayers: [
      { name: 'Virgil van Dijk', pos: 'DF', note: 'Captain; world-class centre-back' },
      { name: 'Ryan Gravenberch', pos: 'MF', note: 'Liverpool anchor; shields and carries' },
      { name: 'Cody Gakpo', pos: 'FW', note: 'Versatile, goal-scoring forward' },
    ],
    strengths: ['Elite defense and midfield', 'Tournament experience', 'Unbeaten in qualifying (27 GF, 4 GA)'],
    weaknesses: ['Less attacking firepower than past sides', 'Three finals, no title', 'Striker question'],
    outlook: 'Favorites to top a balanced Group F.',
  },
  'Japan': {
    rank: 18, coach: 'Hajime Moriyasu', nickname: 'Samurai Blue',
    recent: 'WC22: Round of 16',
    style: 'Fluid 3-4-2-1 with slick technical interplay and fearless pressing — beat England at Wembley in build-up.',
    keyPlayers: [
      { name: 'Takefusa Kubo', pos: 'MF', note: 'Real Sociedad dribbler; chaos in the final third' },
      { name: 'Wataru Endō', pos: 'MF', note: 'Liverpool midfield shield' },
      { name: 'Daizen Maeda', pos: 'FW', note: 'Relentless running and pressing' },
    ],
    strengths: ['Deep pool of Europe-based players', 'Cohesive system', 'Beat England & Scotland recently'],
    weaknesses: ['Can be exposed defensively', 'Finishing in big moments', 'Set-piece defending'],
    outlook: 'Strong contender for a top-two finish in Group F.',
  },
  'Sweden': {
    rank: 38, coach: 'Graham Potter', nickname: 'Blågult',
    recent: 'WC18: Quarterfinals',
    style: 'Built around two elite strikers; pragmatic under new coach Graham Potter with goals from the front.',
    keyPlayers: [
      { name: 'Viktor Gyökeres', pos: 'FW', note: 'Lethal No.9; fired Sweden to the finals late' },
      { name: 'Alexander Isak', pos: 'FW', note: 'Elite movement and finishing' },
      { name: 'Anton Saletros', pos: 'MF', note: 'Midfield balance' },
    ],
    strengths: ['Two world-class strikers', 'Late-qualifying momentum', 'Genuine goal threat'],
    weaknesses: ['New coach (<6 months)', 'Midfield and defensive depth', 'Cohesion'],
    outlook: 'If the strikers click, capable of taking second; a final-day clash with Japan may decide it.',
  },
  'Tunisia': {
    rank: 44, coach: 'Sabri Lamouchi', nickname: 'Carthage Eagles',
    recent: 'WC22: Group stage',
    style: 'Compact, exceptionally well-drilled defensive block that frustrates and counters.',
    keyPlayers: [
      { name: 'Ellyes Skhiri', pos: 'MF', note: 'Controls midfield; Frankfurt regular' },
      { name: 'Hannibal Mejbri', pos: 'MF', note: 'Creative freedom in the final third' },
      { name: 'Aymen Dahmen', pos: 'GK', note: 'Reliable last line' },
    ],
    strengths: ['Best defensive record in African qualifying (9-1-0, 10 clean sheets)', 'Organization', 'Discipline'],
    weaknesses: ['Limited goal threat', 'Struggles to break down deep blocks', 'Final-third quality'],
    outlook: 'Tough to beat but light on goals; outsiders to escape a balanced group.',
  },
  'Belgium': {
    rank: 9, coach: 'Rudi Garcia', nickname: 'Red Devils',
    recent: 'WC22: Group stage',
    style: 'Possession and creativity through a golden-generation core, likely making their last big run together.',
    keyPlayers: [
      { name: 'Kevin De Bruyne', pos: 'MF', note: "Elite playmaker; arguably Belgium's greatest" },
      { name: 'Jérémy Doku', pos: 'FW', note: 'Explosive one-on-one winger' },
      { name: 'Romelu Lukaku', pos: 'FW', note: 'Powerful focal point and top scorer' },
    ],
    strengths: ['World-class creativity', 'Experience', 'Top-10 ranked attacking quality'],
    weaknesses: ['Aging core', 'Defensive frailty', 'History of underachieving'],
    outlook: 'Favorites to win Group G in a likely last dance for the golden generation.',
  },
  'Egypt': {
    rank: 29, coach: 'Hossam Hassan', nickname: 'The Pharaohs',
    recent: 'WC18: Group stage',
    style: 'Back-five low block designed to spring Salah and Marmoush on the counter.',
    keyPlayers: [
      { name: 'Mohamed Salah', pos: 'FW', note: 'Talisman; 2nd all-time Egypt scorer' },
      { name: 'Omar Marmoush', pos: 'FW', note: 'Pace and finishing alongside Salah' },
      { name: 'Mohamed Elneny', pos: 'MF', note: 'Experienced midfield organizer' },
    ],
    strengths: ['A genuine superstar in Salah', 'Counter-attacking threat', 'Defensive structure'],
    weaknesses: ['Over-reliance on Salah', 'Passive approach can invite pressure', 'Creativity beyond the front two'],
    outlook: "Belgium's main challengers and likely to fight for second.",
  },
  'Iran': {
    rank: 21, coach: 'Amir Ghalenoei', nickname: 'Team Melli',
    recent: 'WC22: Group stage',
    style: 'Organized and counter-attacking, built on a solid block and two prolific strikers.',
    keyPlayers: [
      { name: 'Mehdi Taremi', pos: 'FW', note: 'Clinical finisher; qualifying top scorer (5)' },
      { name: 'Sardar Azmoun', pos: 'FW', note: 'Powerful, prolific strike partner' },
      { name: 'Alireza Jahanbakhsh', pos: 'FW', note: 'Experienced wide threat' },
    ],
    strengths: ['Two reliable goalscorers', 'Defensive organization', 'Tournament experience'],
    weaknesses: ['Keeping it solid at the back', 'Squad depth', 'Never past the group stage'],
    outlook: 'Around a two-in-three chance of reaching the knockouts.',
  },
  'New Zealand': {
    rank: 85, coach: 'Darren Bazeley', nickname: 'All Whites',
    style: 'Physical, set-piece-oriented and hard-working — defends deep and uses its aerial presence.',
    keyPlayers: [
      { name: 'Chris Wood', pos: 'FW', note: 'Star man; qualifying top scorer (9)' },
      { name: 'Marko Stamenic', pos: 'MF', note: 'Young midfield driver' },
      { name: 'Tyler Bindon', pos: 'DF', note: 'Promising centre-back' },
    ],
    strengths: ['Aerial and set-piece threat', 'Unbeaten OFC run', 'A proven Premier League scorer'],
    weaknesses: ['Lowest-ranked in the group', 'Limited quality in depth', 'Never past the group stage'],
    outlook: 'Hopes to spring a surprise but faces an uphill task.',
  },
  'Spain': {
    rank: 2, coach: 'Luis de la Fuente', nickname: 'La Roja',
    recent: 'WC22: Round of 16',
    style: 'The complete modern side — suffocating possession, a brilliant midfield and a generational winger.',
    keyPlayers: [
      { name: 'Lamine Yamal', pos: 'FW', note: 'Generational talent; Euro 2024 winner at 18' },
      { name: 'Rodri', pos: 'MF', note: 'Ballon d\'Or-level midfield controller' },
      { name: 'Pedri', pos: 'MF', note: 'Press-resistant midfield brain' },
    ],
    strengths: ['Best midfield in the world', 'Reigning European champions', 'Highest qualifying odds of any team (98.5%)'],
    weaknesses: ['Reliable No.9', 'Youthful inexperience in moments', 'Target on their back'],
    outlook: 'Top-ranked and among the very favorites to win the whole thing.',
  },
  'Cape Verde': {
    rank: 69, coach: 'Bubista', nickname: 'Blue Sharks',
    style: 'Counter-attacking and well-organized; punches massively above its weight for a nation of ~525,000.',
    keyPlayers: [
      { name: 'Dailon Livramento', pos: 'FW', note: 'Match-winner; scored solo goal to beat Cameroon' },
      { name: 'Ryan Mendes', pos: 'FW', note: 'Experienced captain and creator' },
      { name: 'Roberto Lopes', pos: 'DF', note: 'Defensive leader (Shamrock Rovers)' },
    ],
    strengths: ['Fearless underdog spirit', 'Counter-attacking threat', 'Beat Cameroon to qualify'],
    weaknesses: ['Tiny player pool', 'No tournament pedigree', 'Quality gap vs elite'],
    outlook: 'World Cup debutants from a nation of half a million; aiming to compete and shock.',
  },
  'Saudi Arabia': {
    rank: 61, coach: 'Hervé Renard', nickname: 'The Green Falcons',
    recent: 'WC22: Group stage',
    style: "Aggressive pressing side that can trouble big teams when it clicks — but leaves space behind when it doesn't.",
    keyPlayers: [
      { name: 'Salem Al-Dawsari', pos: 'FW', note: 'Captain; scored the 2022 winner vs Argentina' },
      { name: 'Firas Al-Buraikan', pos: 'FW', note: 'Mobile central striker' },
      { name: 'Saud Abdulhamid', pos: 'DF', note: 'Trailblazing right-back (first Saudi in Serie A)' },
    ],
    strengths: ['History of shocking giants (beat Argentina 2022)', 'High press', 'Settled core'],
    weaknesses: ['Space in behind when the press fails', 'Goal threat', 'Defensive depth'],
    outlook: 'Capable of an upset but an outsider to advance from a tough group.',
  },
  'Uruguay': {
    rank: 17, coach: 'Marcelo Bielsa', nickname: 'La Celeste',
    recent: 'WC22: Group stage',
    style: 'Intense, aggressive Bielsa pressing — forces more high turnovers than any other CONMEBOL side.',
    keyPlayers: [
      { name: 'Federico Valverde', pos: 'MF', note: 'All-action Real Madrid engine' },
      { name: 'Darwin Núñez', pos: 'FW', note: 'Relentless, direct centre-forward' },
      { name: 'Ronald Araújo', pos: 'DF', note: 'Powerful Barcelona defender' },
    ],
    strengths: ['Elite midfield and defense', "Bielsa's relentless press (147 high turnovers in qualifying)", 'Big-game talent'],
    weaknesses: ['Finishing consistency', "Bielsa's demanding system can tire legs", 'Discipline'],
    outlook: 'Strongly favored to join Spain in the knockouts and a dark horse to go deep.',
  },
  'France': {
    rank: 1, coach: 'Didier Deschamps', nickname: 'Les Bleus',
    recent: 'WC22: Runners-up',
    style: 'Pragmatic, ruthlessly efficient and absurdly deep — controls games and kills them with elite individuals.',
    keyPlayers: [
      { name: 'Kylian Mbappé', pos: 'FW', note: 'Captain and superstar; pace and goals' },
      { name: 'Aurélien Tchouaméni', pos: 'MF', note: 'Defensive midfield anchor' },
      { name: 'Ousmane Dembélé', pos: 'FW', note: 'Explosive wide threat' },
    ],
    strengths: ['Top-ranked side; tournament pedigree', 'Unmatched squad depth', 'Elite match-winners everywhere'],
    weaknesses: ["Occasional flat spells", "Deschamps' caution", 'Pressure as favorites'],
    outlook: "Among the clear favorites to win it all in Deschamps' farewell tournament.",
  },
  'Senegal': {
    rank: 14, coach: 'Pape Thiaw', nickname: 'Lions of Teranga',
    recent: 'WC22: Round of 16',
    style: 'Powerful, athletic and compact — defensive intensity and transition power through an elite midfield.',
    keyPlayers: [
      { name: 'Nicolas Jackson', pos: 'FW', note: 'Pace and movement up top' },
      { name: 'Pape Matar Sarr', pos: 'MF', note: 'Energetic box-to-box midfielder' },
      { name: 'Kalidou Koulibaly', pos: 'DF', note: 'Defensive leader and organizer' },
    ],
    strengths: ['Physical, athletic spine', 'Compact structure and transition power', '2022 AFCON champions'],
    weaknesses: ['Creativity in tight games', 'Settled No.9', 'Converting dominance to goals'],
    outlook: 'Highest-ranked African side; in a straight fight with Norway for second.',
  },
  'Iraq': {
    rank: 57, coach: 'Graham Arnold', nickname: 'Lions of Mesopotamia',
    style: 'Pragmatic and disciplined — compact defending, controlled risk and opportunistic attacking.',
    keyPlayers: [
      { name: 'Aymen Hussein', pos: 'FW', note: 'Physical focal point and goal threat' },
      { name: 'Zidane Iqbal', pos: 'MF', note: 'Technical midfield creator' },
      { name: 'Jalal Hassan', pos: 'GK', note: 'Reliable last line' },
    ],
    strengths: ['Defensive organization and discipline', 'Emotional motivation (first WC since 1986)', 'Resilience'],
    weaknesses: ['Limited possession quality', 'Goal threat', 'Gulf in class'],
    outlook: 'Back after 40 years; widely tipped to finish bottom but will be hard to break down.',
  },
  'Norway': {
    rank: 31, coach: 'Ståle Solbakken', nickname: '',
    recent: 'WC98: Round of 16',
    style: 'Direct and vertical — get the ball to a world-class striker fast, with Ødegaard controlling tempo.',
    keyPlayers: [
      { name: 'Erling Haaland', pos: 'FW', note: 'All-time top scorer (55); blazing pace and finishing' },
      { name: 'Martin Ødegaard', pos: 'MF', note: 'Creative engine; the vital link to Haaland' },
      { name: 'Antonio Nusa', pos: 'FW', note: 'Direct young wide threat' },
      { name: 'Alexander Sørloth', pos: 'FW', note: 'Powerful second striker' },
    ],
    strengths: ['Elite match-winners in the spine', 'Perfect qualifying (8-0-0, 37 GF)', 'Goal threat vs anyone'],
    weaknesses: ['Heavy reliance on two stars', 'Unproven depth', 'Can be exposed by elite sides'],
    outlook: "Dark horse back after 28 years; nobody wants to face Haaland.",
  },
  'Argentina': {
    rank: 3, coach: 'Lionel Scaloni', nickname: 'La Albiceleste',
    style: 'Fluid 4-3-3/4-4-2 hybrid — collective pressing, rapid transitions, controls tempo or counters ruthlessly.',
    keyPlayers: [
      { name: 'Lionel Messi', pos: 'FW', note: 'Talisman; vision and clutch delivery in a record 6th WC' },
      { name: 'Lautaro Martínez', pos: 'FW', note: '2024 Copa América top scorer' },
      { name: 'Alexis Mac Allister', pos: 'MF', note: 'Recovery and creativity in midfield' },
      { name: 'Emiliano Martínez', pos: 'GK', note: 'Decisive big-game shot-stopper' },
    ],
    strengths: ['Most tactically disciplined side in the field', 'Elite talent across every line', 'Exceptional chemistry'],
    weaknesses: ["Messi's age", 'Centre-back depth', 'Weight of defending the title'],
    outlook: 'Defending champions and co-favorites; tournament know-how is unmatched.',
  },
  'Algeria': {
    rank: 28, coach: 'Vladimir Petković', nickname: 'Les Fennecs (Desert Foxes)',
    style: 'Technically gifted and attack-minded, built around quick, creative forwards.',
    keyPlayers: [
      { name: 'Mohammed Amoura', pos: 'FW', note: 'Top scorer in CAF qualifying (10 in 10)' },
      { name: 'Riyad Mahrez', pos: 'FW', note: 'Experienced match-winner out wide' },
      { name: 'Ismaël Bennacer', pos: 'MF', note: 'Tempo-setting midfielder' },
    ],
    strengths: ['Attacking flair and pace', 'Best-ever qualifying (8 wins)', 'Big-game experience in Mahrez'],
    weaknesses: ['Defensive consistency', 'Failed to escape the group in 2014/last appearance', 'Balance'],
    outlook: 'Best-placed to chase second behind Argentina in Group J.',
  },
  'Austria': {
    rank: 24, coach: 'Ralf Rangnick', nickname: 'Das Team',
    recent: 'WC98: Group stage',
    style: "Rangnick's relentless, aggressive pressing system — built specifically for tournament football.",
    keyPlayers: [
      { name: 'David Alaba', pos: 'DF', note: 'Captain and defensive leader; 113+ caps' },
      { name: 'Marko Arnautović', pos: 'FW', note: 'All-time top scorer (47)' },
      { name: 'Konrad Laimer', pos: 'MF', note: 'Energetic pressing midfielder' },
    ],
    strengths: ['Cohesive, intense pressing identity', 'Elite coach', 'Built for tournament demands'],
    weaknesses: ['Aging key players', 'Goal threat depth', 'Stamina across a long tournament'],
    outlook: 'Second favorites in Group J (67% to advance) behind Argentina.',
  },
  'Jordan': {
    rank: 63, coach: 'Jamal Sellami', nickname: 'Al-Nashama',
    style: 'Well-organized and counter-attacking — defensively disciplined with a real threat on the break.',
    keyPlayers: [
      { name: 'Musa Al-Tamari', pos: 'FW', note: 'Counter-attacking spark; the danger man' },
      { name: 'Yazan Al-Naimat', pos: 'FW', note: 'Mobile striker' },
      { name: 'Nour Al-Rawabdeh', pos: 'MF', note: 'Midfield runner' },
    ],
    strengths: ['Defensive organization', 'Counter-attack through Al-Tamari', 'Underdog freedom'],
    weaknesses: ['Lowest-ranked in the group', 'WC debutants', 'Quality gap vs Argentina/Austria'],
    outlook: 'First World Cup; will defend deep and look to spring a surprise.',
  },
  'Portugal': {
    rank: 5, coach: 'Roberto Martínez', nickname: 'A Seleção das Quinas',
    recent: 'WC22: Quarterfinals',
    style: 'Talent-laden possession side with elite creativity and depth across every position.',
    keyPlayers: [
      { name: 'Bruno Fernandes', pos: 'MF', note: "Captain; one of the PL's top chance creators" },
      { name: 'Cristiano Ronaldo', pos: 'FW', note: 'All-time great chasing a final WC' },
      { name: 'Vitinha', pos: 'MF', note: 'PSG midfield controller' },
    ],
    strengths: ['Outstanding squad depth', 'Elite creativity', 'Won the 2025 Nations League'],
    weaknesses: ['Balancing veterans and youth', 'Defensive lapses', 'Knockout scar tissue'],
    outlook: 'Clear Group K favorites and genuine contenders to win it all.',
  },
  'DR Congo': {
    rank: 46, coach: 'Sébastien Desabre', nickname: 'Léopards',
    style: 'Aggressive high press that wins the ball in dangerous areas and attacks with pace.',
    keyPlayers: [
      { name: 'Yoane Wissa', pos: 'FW', note: 'Premier League-caliber forward (Newcastle)' },
      { name: 'Chancel Mbemba', pos: 'DF', note: 'Captain and defensive anchor' },
      { name: 'Cédric Bakambu', pos: 'FW', note: 'Experienced goalscorer' },
    ],
    strengths: ['High, aggressive press', 'Pace in attack', 'Physicality'],
    weaknesses: ['Defensive discipline when stretched', 'Tournament inexperience (first since 1974)', 'Consistency'],
    outlook: 'Outsiders in Group K but capable of troubling Colombia for second.',
  },
  'Uzbekistan': {
    rank: 50, coach: 'Fabio Cannavaro', nickname: 'White Wolves',
    style: 'Organized 3-4-2-1 under Cannavaro — defensive discipline, structured transitions, focal-point striker.',
    keyPlayers: [
      { name: 'Eldor Shomurodov', pos: 'FW', note: 'Captain and all-time top scorer (44)' },
      { name: 'Abdukodir Khusanov', pos: 'DF', note: 'Exciting Man City defender at 22' },
      { name: 'Jaloliddin Masharipov', pos: 'MF', note: 'Creative attacking midfielder' },
    ],
    strengths: ['Defensive organization', 'A World Cup-winning coach', 'A proven goalscorer up top'],
    weaknesses: ['First WC — total inexperience', 'Squad depth', 'Final-third quality'],
    outlook: 'World Cup debutants; a knockout place would be a major achievement.',
  },
  'Colombia': {
    rank: 13, coach: 'Néstor Lorenzo', nickname: 'Los Cafeteros',
    recent: 'WC18: Round of 16',
    style: 'Technical, creative and balanced — controls games through midfield with dangerous wide forwards.',
    keyPlayers: [
      { name: 'Luis Díaz', pos: 'FW', note: 'Dynamic winger; 7 goals in CONMEBOL qualifying' },
      { name: 'James Rodríguez', pos: 'MF', note: 'Captain and chief creator; led qualifying assists (7)' },
      { name: 'Jhon Lucumí', pos: 'DF', note: 'Composed centre-back' },
    ],
    strengths: ['Excellent creativity and balance', 'Match-winners in Díaz and James', 'Strong qualifying campaign'],
    weaknesses: ["Reliance on James' form/fitness", 'Defensive depth', 'Killer instinct'],
    outlook: 'Strong favorites for second behind Portugal and a dark horse to go further.',
  },
  'England': {
    rank: 4, coach: 'Thomas Tuchel', nickname: 'Three Lions',
    recent: 'WC22: Quarterfinals',
    style: 'Defensively elite and pragmatic under Tuchel — built on a watertight base and world-class attackers.',
    keyPlayers: [
      { name: 'Harry Kane', pos: 'FW', note: "All-time top scorer (78); Ballon d'Or contender" },
      { name: 'Jude Bellingham', pos: 'MF', note: 'Driving, goal-scoring midfielder' },
      { name: 'Bukayo Saka', pos: 'FW', note: 'Direct, productive wide threat' },
    ],
    strengths: ['Best defensive record in European qualifying (9 clean sheets)', 'Elite attacking talent', 'Squad depth'],
    weaknesses: ['Tournament knockout history', 'Midfield balance', 'Pressure to end 60-year wait'],
    outlook: 'Among the favorites; 3rd most likely of any team to top their group.',
  },
  'Croatia': {
    rank: 11, coach: 'Zlatko Dalić', nickname: 'Vatreni (Blazers)',
    recent: 'WC22: 3rd place',
    style: 'Midfield-dominant and game-smart — controls tempo and grinds out deep tournament runs.',
    keyPlayers: [
      { name: 'Luka Modrić', pos: 'MF', note: 'Greatest-ever Croatian; nears 200 caps' },
      { name: 'Joško Gvardiol', pos: 'DF', note: 'Man City defender; back-line anchor' },
      { name: 'Mateo Kovačić', pos: 'MF', note: 'Press-resistant midfield partner' },
    ],
    strengths: ['Elite midfield control', 'Serial tournament over-performers (2018 finalists, 2022 3rd)', 'Game management'],
    weaknesses: ['Aging core', 'Lack of a prolific striker', 'Legs over a long tournament'],
    outlook: 'Strongly favored to reach the knockouts again from Group L.',
  },
  'Ghana': {
    rank: 74, coach: 'Otto Addo', nickname: 'Black Stars',
    recent: 'WC22: Group stage',
    style: 'Athletic and direct, with pace on the break and a mix of physicality and flair.',
    keyPlayers: [
      { name: 'Antoine Semenyo', pos: 'FW', note: 'In-form forward; 21 G/6 A across clubs this season' },
      { name: 'Mohammed Kudus', pos: 'MF', note: 'Dynamic dribbler and creator' },
      { name: 'Jordan Ayew', pos: 'FW', note: 'Captain and experienced leader (118 caps)' },
    ],
    strengths: ['Pace and directness', 'In-form attacking talent', 'A reaching-knockouts pedigree (2010 QF)'],
    weaknesses: ['Defensive reliability', 'Consistency', 'Lowest-ranked of the contenders here'],
    outlook: 'Underdogs in Group L but with the attacking talent to spring a surprise.',
  },
  'Panama': {
    rank: 33, coach: 'Thomas Christiansen', nickname: 'La Marea Roja',
    style: 'Energetic, high-pressing 3-4-3 that leads its region in turnovers and pressed sequences.',
    keyPlayers: [
      { name: 'Adalberto Carrasquilla', pos: 'MF', note: 'Midfield engine and creator' },
      { name: 'José Fajardo', pos: 'FW', note: 'Mobile central striker' },
      { name: 'César Blackman', pos: 'DF', note: 'Energetic wing-back' },
    ],
    strengths: ['High press (led region in turnovers)', 'Risen from 81st to 33rd in six years', 'Cohesive system'],
    weaknesses: ['Limited elite individual quality', 'Goal threat vs top defenses', 'WC inexperience'],
    outlook: "A well-drilled, fast-rising side aiming to shock the group's big two.",
  },
};

// FIFA World Rankings (April 1 2026 update)
export const FIFA_RANK: Record<string, number> = {
  'France': 1, 'Spain': 2, 'Argentina': 3, 'England': 4, 'Portugal': 5,
  'Brazil': 6, 'Netherlands': 7, 'Morocco': 8, 'Belgium': 9, 'Germany': 10,
  'Croatia': 11, 'Colombia': 13, 'Senegal': 14, 'Mexico': 15, 'USA': 16,
  'Uruguay': 17, 'Japan': 18, 'Switzerland': 19, 'Iran': 21, 'Ecuador': 23,
  'Austria': 24, 'South Korea': 25, 'Turkey': 26, 'Australia': 27,
  'Algeria': 28, 'Egypt': 29, 'Canada': 30, 'Norway': 31, 'Ivory Coast': 34,
  'Panama': 33, 'Sweden': 38, 'Paraguay': 40, 'Czechia': 41, 'Scotland': 43,
  'Tunisia': 44, 'DR Congo': 46, 'Uzbekistan': 50, 'Qatar': 55, 'Iraq': 57,
  'South Africa': 60, 'Saudi Arabia': 61, 'Jordan': 63, 'Bosnia and Herz.': 65,
  'Cape Verde': 69, 'Ghana': 74, 'Curaçao': 82, 'Haiti': 83, 'New Zealand': 85,
};

// Head-to-head records. Key: 'TeamA|TeamB' — first team's W/D/L/GF/GA perspective.
export const H2H: Record<string, H2HEntry> = {
  'Mexico|South Africa': { comp: {w:1,d:1,l:0,gf:4,ga:2}, friendly: {w:3,d:1,l:1,gf:9,ga:5} },
  'South Korea|Czechia': { comp: {w:1,d:1,l:1,gf:4,ga:4}, friendly: {w:2,d:2,l:3,gf:9,ga:11} },
  'Mexico|South Korea': { comp: {w:3,d:0,l:1,gf:9,ga:5}, friendly: {w:5,d:2,l:2,gf:19,ga:12} },
  'South Africa|Czechia': { friendly: {w:1,d:0,l:1,gf:2,ga:3} },
  'Mexico|Czechia': { comp: {w:1,d:0,l:1,gf:3,ga:3}, friendly: {w:3,d:1,l:2,gf:9,ga:8} },
  'South Africa|South Korea': { comp: {w:0,d:1,l:1,gf:1,ga:3}, friendly: {w:1,d:1,l:2,gf:5,ga:7} },
  'Canada|Bosnia and Herz.': { friendly: {w:1,d:0,l:1,gf:2,ga:3} },
  'Qatar|Switzerland': { comp: {w:0,d:0,l:1,gf:0,ga:3}, friendly: {w:0,d:1,l:1,gf:1,ga:4} },
  'Canada|Qatar': { friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'Bosnia and Herz.|Switzerland': { comp: {w:0,d:2,l:2,gf:5,ga:8}, friendly: {w:1,d:1,l:2,gf:5,ga:8} },
  'Canada|Switzerland': { friendly: {w:0,d:1,l:2,gf:2,ga:5} },
  'Bosnia and Herz.|Qatar': { friendly: {w:1,d:0,l:0,gf:3,ga:1} },
  'Brazil|Morocco': { comp: {w:1,d:0,l:0,gf:1,ga:0}, friendly: {w:3,d:0,l:0,gf:8,ga:1} },
  'Haiti|Scotland': { friendly: {w:0,d:0,l:1,gf:0,ga:1} },
  'Brazil|Haiti': { comp: {w:1,d:0,l:0,gf:7,ga:1}, friendly: {w:3,d:0,l:0,gf:12,ga:0} },
  'Morocco|Scotland': { friendly: {w:1,d:1,l:0,gf:2,ga:1} },
  'Brazil|Scotland': { comp: {w:0,d:1,l:0,gf:0,ga:0}, friendly: {w:4,d:2,l:2,gf:15,ga:9} },
  'Morocco|Haiti': { friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'USA|Paraguay': { comp: {w:1,d:1,l:1,gf:4,ga:4}, friendly: {w:3,d:3,l:2,gf:13,ga:11} },
  'Australia|Turkey': { comp: {w:1,d:0,l:1,gf:2,ga:3}, friendly: {w:2,d:1,l:2,gf:8,ga:9} },
  'USA|Australia': { comp: {w:2,d:0,l:1,gf:5,ga:4}, friendly: {w:6,d:3,l:2,gf:22,ga:13} },
  'Paraguay|Turkey': { friendly: {w:1,d:1,l:0,gf:3,ga:1} },
  'USA|Turkey': { friendly: {w:3,d:2,l:1,gf:11,ga:7} },
  'Paraguay|Australia': { friendly: {w:1,d:1,l:1,gf:4,ga:4} },
  'Germany|Curaçao': { friendly: {w:1,d:0,l:0,gf:3,ga:0} },
  'Ivory Coast|Ecuador': { comp: {w:1,d:0,l:0,gf:2,ga:1}, friendly: {w:1,d:1,l:0,gf:3,ga:2} },
  'Germany|Ivory Coast': { comp: {w:1,d:0,l:0,gf:5,ga:2}, friendly: {w:3,d:1,l:1,gf:12,ga:6} },
  'Germany|Ecuador': { comp: {w:2,d:0,l:1,gf:5,ga:3}, friendly: {w:3,d:1,l:1,gf:12,ga:6} },
  'Netherlands|Japan': { comp: {w:1,d:0,l:0,gf:2,ga:1}, friendly: {w:3,d:1,l:1,gf:10,ga:5} },
  'Sweden|Tunisia': { comp: {w:1,d:0,l:0,gf:3,ga:1}, friendly: {w:2,d:0,l:0,gf:5,ga:1} },
  'Netherlands|Sweden': { comp: {w:5,d:3,l:3,gf:21,ga:18}, friendly: {w:6,d:2,l:5,gf:27,ga:24} },
  'Japan|Tunisia': { comp: {w:1,d:0,l:1,gf:2,ga:2}, friendly: {w:2,d:0,l:0,gf:4,ga:1} },
  'Netherlands|Tunisia': { comp: {w:1,d:0,l:0,gf:2,ga:1}, friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'Japan|Sweden': { friendly: {w:0,d:1,l:2,gf:2,ga:6} },
  'Belgium|Egypt': { comp: {w:1,d:0,l:0,gf:3,ga:1}, friendly: {w:2,d:1,l:0,gf:5,ga:2} },
  'Iran|New Zealand': { comp: {w:1,d:0,l:0,gf:2,ga:0}, friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'Belgium|Iran': { comp: {w:2,d:0,l:0,gf:4,ga:1}, friendly: {w:1,d:1,l:0,gf:4,ga:2} },
  'Egypt|New Zealand': { friendly: {w:1,d:0,l:1,gf:2,ga:2} },
  'Belgium|New Zealand': { comp: {w:1,d:0,l:0,gf:1,ga:0}, friendly: {w:2,d:0,l:0,gf:5,ga:1} },
  'Egypt|Iran': { friendly: {w:1,d:2,l:0,gf:3,ga:2} },
  'Spain|Cape Verde': { friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'Saudi Arabia|Uruguay': { friendly: {w:0,d:1,l:2,gf:2,ga:5} },
  'Spain|Saudi Arabia': { comp: {w:1,d:0,l:0,gf:3,ga:0}, friendly: {w:3,d:1,l:0,gf:12,ga:2} },
  'Cape Verde|Uruguay': { friendly: {w:0,d:0,l:1,gf:0,ga:2} },
  'Spain|Uruguay': { comp: {w:3,d:2,l:3,gf:14,ga:12}, friendly: {w:6,d:3,l:3,gf:22,ga:16} },
  'Cape Verde|Saudi Arabia': { friendly: {w:1,d:0,l:0,gf:1,ga:0} },
  'France|Senegal': { comp: {w:0,d:0,l:1,gf:0,ga:1}, friendly: {w:3,d:1,l:1,gf:9,ga:4} },
  'Iraq|Norway': { comp: {w:0,d:0,l:1,gf:0,ga:1}, friendly: {w:0,d:0,l:2,gf:0,ga:4} },
  'France|Iraq': { friendly: {w:2,d:0,l:0,gf:6,ga:0} },
  'Senegal|Norway': { friendly: {w:1,d:0,l:1,gf:2,ga:2} },
  'France|Norway': { comp: {w:5,d:2,l:2,gf:18,ga:10}, friendly: {w:5,d:1,l:2,gf:18,ga:9} },
  'Senegal|Iraq': { friendly: {w:1,d:1,l:0,gf:3,ga:1} },
  'Argentina|Algeria': { friendly: {w:1,d:1,l:0,gf:4,ga:2} },
  'Austria|Jordan': { friendly: {w:1,d:0,l:0,gf:4,ga:1} },
  'Argentina|Austria': { comp: {w:2,d:1,l:1,gf:7,ga:5}, friendly: {w:4,d:3,l:2,gf:17,ga:12} },
  'Algeria|Jordan': { friendly: {w:2,d:0,l:0,gf:4,ga:1} },
  'Argentina|Jordan': { friendly: {w:1,d:0,l:0,gf:5,ga:0} },
  'Algeria|Austria': { friendly: {w:0,d:1,l:1,gf:1,ga:2} },
  'Portugal|DR Congo': { friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'Uzbekistan|Colombia': { friendly: {w:0,d:0,l:1,gf:0,ga:3} },
  'Portugal|Uzbekistan': { friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'DR Congo|Colombia': { friendly: {w:0,d:1,l:1,gf:2,ga:3} },
  'Portugal|Colombia': { friendly: {w:2,d:2,l:1,gf:7,ga:5} },
  'DR Congo|Uzbekistan': { friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'England|Croatia': { comp: {w:3,d:0,l:3,gf:9,ga:8}, friendly: {w:2,d:1,l:0,gf:6,ga:2} },
  'Ghana|Panama': { friendly: {w:2,d:0,l:0,gf:5,ga:1} },
  'England|Ghana': { comp: {w:1,d:0,l:0,gf:1,ga:0}, friendly: {w:4,d:1,l:0,gf:14,ga:4} },
  'Croatia|Panama': { friendly: {w:1,d:0,l:0,gf:2,ga:0} },
  'England|Panama': { comp: {w:1,d:0,l:0,gf:6,ga:1} },
  'Croatia|Ghana': { friendly: {w:1,d:1,l:0,gf:3,ga:2} },
  'Brazil|Ecuador': { comp: {w:22,d:4,l:2,gf:72,ga:13}, friendly: {w:6,d:3,l:0,gf:18,ga:5} },
  'Brazil|Uruguay': { comp: {w:30,d:14,l:18,gf:101,ga:85}, friendly: {w:16,d:8,l:9,gf:63,ga:46} },
  'Brazil|Argentina': { comp: {w:22,d:13,l:19,gf:83,ga:76}, friendly: {w:18,d:13,l:22,gf:76,ga:83} },
  'Brazil|Colombia': { comp: {w:17,d:8,l:3,gf:48,ga:21}, friendly: {w:5,d:4,l:1,gf:17,ga:10} },
  'Brazil|Paraguay': { comp: {w:31,d:12,l:8,gf:104,ga:51}, friendly: {w:20,d:9,l:4,gf:64,ga:27} },
  'Ecuador|Uruguay': { comp: {w:5,d:3,l:8,gf:18,ga:26}, friendly: {w:1,d:2,l:1,gf:4,ga:5} },
  'Ecuador|Argentina': { comp: {w:5,d:5,l:22,gf:22,ga:73}, friendly: {w:1,d:2,l:3,gf:3,ga:7} },
  'Ecuador|Colombia': { comp: {w:5,d:5,l:10,gf:18,ga:32}, friendly: {w:1,d:2,l:2,gf:5,ga:9} },
  'Ecuador|Paraguay': { comp: {w:4,d:4,l:5,gf:16,ga:18}, friendly: {w:1,d:1,l:1,gf:4,ga:5} },
  'Uruguay|Argentina': { comp: {w:50,d:24,l:65,gf:222,ga:285}, friendly: {w:9,d:22,l:27,gf:63,ga:97} },
  'Uruguay|Colombia': { comp: {w:7,d:4,l:4,gf:23,ga:18}, friendly: {w:2,d:2,l:1,gf:7,ga:6} },
  'Uruguay|Paraguay': { comp: {w:12,d:8,l:7,gf:42,ga:32}, friendly: {w:5,d:4,l:2,gf:16,ga:10} },
  'Argentina|Colombia': { comp: {w:20,d:7,l:7,gf:68,ga:33}, friendly: {w:6,d:2,l:3,gf:21,ga:13} },
  'Argentina|Paraguay': { comp: {w:28,d:18,l:10,gf:100,ga:57}, friendly: {w:9,d:6,l:4,gf:32,ga:22} },
  'Colombia|Paraguay': { comp: {w:10,d:3,l:3,gf:21,ga:14}, friendly: {w:3,d:1,l:1,gf:10,ga:7} },
  'Brazil|Germany': { comp: {w:2,d:0,l:2,gf:8,ga:14}, friendly: {w:11,d:5,l:3,gf:36,ga:18} },
  'Brazil|France': { comp: {w:1,d:1,l:3,gf:4,ga:11}, friendly: {w:5,d:2,l:3,gf:9,ga:9} },
  'Brazil|England': { comp: {w:4,d:1,l:0,gf:5,ga:2}, friendly: {w:14,d:7,l:4,gf:40,ga:23} },
  'Brazil|Spain': { comp: {w:3,d:1,l:1,gf:9,ga:7}, friendly: {w:2,d:1,l:0,gf:5,ga:2} },
  'Brazil|Netherlands': { comp: {w:3,d:1,l:3,gf:10,ga:10}, friendly: {w:2,d:2,l:1,gf:8,ga:6} },
  'Brazil|Portugal': { comp: {w:0,d:1,l:2,gf:1,ga:5}, friendly: {w:2,d:1,l:1,gf:7,ga:5} },
  'Brazil|Belgium': { comp: {w:1,d:0,l:1,gf:2,ga:2}, friendly: {w:2,d:0,l:1,gf:12,ga:6} },
  'Argentina|France': { comp: {w:4,d:2,l:3,gf:13,ga:16}, friendly: {w:3,d:1,l:0,gf:6,ga:3} },
  'Argentina|Germany': { comp: {w:5,d:3,l:5,gf:15,ga:17}, friendly: {w:5,d:4,l:3,gf:17,ga:15} },
  'Argentina|England': { comp: {w:3,d:1,l:4,gf:11,ga:12}, friendly: {w:0,d:0,l:2,gf:0,ga:5} },
  'Argentina|Netherlands': { comp: {w:3,d:3,l:2,gf:12,ga:11}, friendly: {w:2,d:1,l:1,gf:7,ga:5} },
  'Argentina|Spain': { comp: {w:2,d:1,l:2,gf:8,ga:9}, friendly: {w:4,d:2,l:1,gf:14,ga:8} },
  'Argentina|Portugal': { comp: {w:1,d:0,l:0,gf:2,ga:1}, friendly: {w:4,d:1,l:1,gf:11,ga:7} },
  'Argentina|Croatia': { comp: {w:3,d:0,l:1,gf:5,ga:4}, friendly: {w:1,d:1,l:1,gf:5,ga:5} },
  'Uruguay|France': { comp: {w:3,d:3,l:1,gf:8,ga:7}, friendly: {w:0,d:1,l:0,gf:1,ga:1} },
  'Uruguay|Germany': { comp: {w:1,d:0,l:5,gf:8,ga:18}, friendly: {w:0,d:1,l:1,gf:2,ga:5} },
  'Uruguay|England': { comp: {w:2,d:1,l:0,gf:4,ga:2}, friendly: {w:3,d:3,l:3,gf:10,ga:10} },
  'Uruguay|Portugal': { comp: {w:1,d:0,l:1,gf:2,ga:2}, friendly: {w:1,d:1,l:1,gf:4,ga:5} },
  'Colombia|France': { friendly: {w:1,d:0,l:3,gf:5,ga:7} },
  'Colombia|England': { comp: {w:0,d:1,l:2,gf:1,ga:4}, friendly: {w:0,d:2,l:0,gf:1,ga:1} },
  'Colombia|Germany': { comp: {w:0,d:1,l:0,gf:1,ga:1}, friendly: {w:1,d:1,l:1,gf:7,ga:9} },
  'Paraguay|France': { comp: {w:0,d:0,l:1,gf:0,ga:1}, friendly: {w:0,d:1,l:1,gf:1,ga:3} },
  'Morocco|Spain': { comp: {w:1,d:2,l:2,gf:4,ga:6} },
  'Morocco|France': { comp: {w:0,d:0,l:1,gf:0,ga:2}, friendly: {w:1,d:3,l:3,gf:9,ga:12} },
  'Morocco|Portugal': { comp: {w:2,d:0,l:1,gf:4,ga:2} },
  'Morocco|Belgium': { comp: {w:1,d:0,l:0,gf:2,ga:0}, friendly: {w:1,d:0,l:1,gf:2,ga:3} },
  'Morocco|Germany': { comp: {w:0,d:0,l:1,gf:0,ga:2}, friendly: {w:0,d:1,l:1,gf:1,ga:3} },
  'Morocco|Netherlands': { comp: {w:0,d:0,l:1,gf:0,ga:2}, friendly: {w:0,d:0,l:2,gf:1,ga:6} },
  'Morocco|England': { comp: {w:0,d:0,l:0,gf:0,ga:0}, friendly: {w:0,d:1,l:1,gf:1,ga:3} },
  'Morocco|Argentina': { friendly: {w:0,d:0,l:1,gf:0,ga:2} },
  'Senegal|France': { comp: {w:1,d:0,l:0,gf:1,ga:0}, friendly: {w:0,d:1,l:0,gf:0,ga:0} },
  'Senegal|England': { comp: {w:0,d:0,l:1,gf:0,ga:3} },
  'Senegal|Belgium': { comp: {w:0,d:0,l:0,gf:0,ga:0}, friendly: {w:1,d:1,l:1,gf:3,ga:3} },
  'Egypt|Germany': { comp: {w:0,d:0,l:2,gf:0,ga:6}, friendly: {w:0,d:1,l:1,gf:1,ga:5} },
  'Iran|Portugal': { comp: {w:0,d:0,l:1,gf:1,ga:2}, friendly: {w:0,d:0,l:1,gf:0,ga:1} },
  'Iran|Spain': { comp: {w:0,d:0,l:1,gf:0,ga:1}, friendly: {w:0,d:0,l:1,gf:0,ga:2} },
  'Iran|Argentina': { comp: {w:0,d:0,l:2,gf:0,ga:4}, friendly: {w:0,d:1,l:0,gf:1,ga:1} },
  'Iran|USA': { comp: {w:1,d:0,l:1,gf:2,ga:2}, friendly: {w:0,d:1,l:0,gf:1,ga:1} },
  'Mexico|Argentina': { comp: {w:2,d:5,l:14,gf:12,ga:43}, friendly: {w:2,d:7,l:2,gf:11,ga:9} },
  'Mexico|Brazil': { comp: {w:2,d:2,l:12,gf:12,ga:35}, friendly: {w:8,d:5,l:10,gf:28,ga:36} },
  'Mexico|Germany': { comp: {w:1,d:1,l:4,gf:5,ga:13}, friendly: {w:1,d:4,l:2,gf:7,ga:11} },
  'Mexico|France': { comp: {w:0,d:1,l:3,gf:3,ga:9}, friendly: {w:2,d:0,l:0,gf:5,ga:2} },
  'Mexico|Spain': { comp: {w:1,d:1,l:3,gf:4,ga:10}, friendly: {w:3,d:3,l:2,gf:11,ga:10} },
  'Mexico|England': { comp: {w:0,d:0,l:1,gf:0,ga:3}, friendly: {w:2,d:2,l:4,gf:9,ga:17} },
  'Japan|Germany': { comp: {w:1,d:0,l:0,gf:2,ga:1}, friendly: {w:1,d:2,l:1,gf:5,ga:7} },
  'Japan|Spain': { comp: {w:1,d:0,l:0,gf:2,ga:1}, friendly: {w:0,d:0,l:3,gf:0,ga:5} },
  'Japan|Belgium': { comp: {w:0,d:1,l:1,gf:4,ga:5}, friendly: {w:1,d:0,l:1,gf:4,ga:1} },
  'Japan|France': { comp: {w:0,d:0,l:1,gf:0,ga:1}, friendly: {w:0,d:1,l:2,gf:2,ga:6} },
  'Japan|Argentina': { comp: {w:0,d:0,l:1,gf:1,ga:2}, friendly: {w:0,d:1,l:3,gf:2,ga:8} },
  'Japan|England': { comp: {w:0,d:0,l:0,gf:0,ga:0}, friendly: {w:2,d:2,l:2,gf:7,ga:9} },
  'Japan|Netherlands': { comp: {w:0,d:0,l:1,gf:0,ga:3}, friendly: {w:1,d:2,l:2,gf:7,ga:12} },
  'Japan|Croatia': { comp: {w:0,d:1,l:0,gf:1,ga:1}, friendly: {w:1,d:0,l:1,gf:2,ga:2} },
  'South Korea|Germany': { comp: {w:1,d:0,l:2,gf:4,ga:8}, friendly: {w:0,d:1,l:1,gf:2,ga:6} },
  'South Korea|Spain': { comp: {w:1,d:0,l:1,gf:2,ga:1}, friendly: {w:0,d:0,l:2,gf:1,ga:5} },
  'South Korea|USA': { comp: {w:1,d:1,l:1,gf:3,ga:3}, friendly: {w:2,d:1,l:1,gf:5,ga:4} },
  'Australia|France': { comp: {w:1,d:0,l:2,gf:2,ga:5}, friendly: {w:0,d:1,l:1,gf:1,ga:7} },
  'Australia|Argentina': { comp: {w:0,d:0,l:3,gf:2,ga:9}, friendly: {w:1,d:1,l:2,gf:5,ga:5} },
  'Australia|England': { comp: {w:0,d:0,l:0,gf:0,ga:0}, friendly: {w:2,d:3,l:5,gf:11,ga:19} },
  'Australia|Germany': { comp: {w:0,d:0,l:2,gf:3,ga:11}, friendly: {w:1,d:1,l:3,gf:9,ga:16} },
  'Australia|Netherlands': { comp: {w:0,d:0,l:1,gf:1,ga:2}, friendly: {w:0,d:1,l:2,gf:2,ga:7} },
  'USA|Germany': { comp: {w:0,d:0,l:3,gf:1,ga:5}, friendly: {w:4,d:0,l:4,gf:12,ga:14} },
  'USA|France': { friendly: {w:0,d:1,l:3,gf:1,ga:11} },
  'USA|England': { comp: {w:2,d:2,l:1,gf:3,ga:5}, friendly: {w:0,d:0,l:6,gf:4,ga:34} },
  'USA|Spain': { comp: {w:1,d:0,l:1,gf:2,ga:3}, friendly: {w:0,d:0,l:5,gf:0,ga:17} },
  'USA|Portugal': { comp: {w:1,d:2,l:0,gf:4,ga:3} },
  'USA|Brazil': { comp: {w:0,d:1,l:3,gf:2,ga:9}, friendly: {w:1,d:2,l:4,gf:8,ga:17} },
  'USA|Argentina': { comp: {w:0,d:0,l:4,gf:1,ga:17}, friendly: {w:2,d:2,l:2,gf:5,ga:8} },
  'USA|Belgium': { comp: {w:0,d:0,l:1,gf:1,ga:2}, friendly: {w:1,d:2,l:2,gf:5,ga:8} },
  'USA|Netherlands': { comp: {w:0,d:0,l:1,gf:1,ga:3}, friendly: {w:1,d:1,l:2,gf:5,ga:8} },
  'Canada|Belgium': { comp: {w:0,d:0,l:1,gf:0,ga:1}, friendly: {w:0,d:0,l:1,gf:0,ga:2} },
  'Canada|France': { comp: {w:0,d:0,l:1,gf:0,ga:2}, friendly: {w:0,d:0,l:2,gf:0,ga:5} },
  'Canada|Morocco': { comp: {w:0,d:0,l:1,gf:0,ga:2}, friendly: {w:0,d:0,l:0,gf:0,ga:0} },
  'Canada|Croatia': { comp: {w:0,d:1,l:0,gf:1,ga:1}, friendly: {w:0,d:0,l:0,gf:0,ga:0} },
  'Canada|Netherlands': { comp: {w:0,d:0,l:1,gf:0,ga:2}, friendly: {w:1,d:0,l:1,gf:2,ga:4} },
  'Saudi Arabia|Argentina': { comp: {w:1,d:0,l:2,gf:3,ga:7}, friendly: {w:0,d:1,l:0,gf:0,ga:0} },
  'Saudi Arabia|Mexico': { comp: {w:0,d:0,l:1,gf:0,ga:2}, friendly: {w:1,d:0,l:1,gf:2,ga:3} },
  'Mexico|Canada': { comp: {w:34,d:9,l:5,gf:115,ga:41}, friendly: {w:12,d:5,l:8,gf:42,ga:32} },
  'Mexico|USA': { comp: {w:21,d:12,l:14,gf:75,ga:59}, friendly: {w:15,d:8,l:10,gf:55,ga:43} },
  'USA|Canada': { comp: {w:14,d:8,l:5,gf:46,ga:25}, friendly: {w:12,d:5,l:8,gf:39,ga:30} },
  'Germany|Netherlands': { comp: {w:12,d:9,l:6,gf:46,ga:38}, friendly: {w:6,d:9,l:6,gf:44,ga:41} },
  'Germany|Belgium': { comp: {w:6,d:2,l:3,gf:20,ga:14}, friendly: {w:14,d:7,l:9,gf:55,ga:43} },
  'Germany|Spain': { comp: {w:5,d:4,l:7,gf:18,ga:24}, friendly: {w:4,d:5,l:2,gf:16,ga:11} },
  'Germany|France': { comp: {w:5,d:3,l:6,gf:20,ga:22}, friendly: {w:6,d:4,l:9,gf:28,ga:39} },
  'Germany|Austria': { comp: {w:5,d:1,l:2,gf:17,ga:11}, friendly: {w:7,d:2,l:2,gf:25,ga:10} },
  'Germany|Portugal': { comp: {w:4,d:1,l:4,gf:16,ga:17}, friendly: {w:5,d:3,l:3,gf:18,ga:15} },
  'Germany|England': { comp: {w:6,d:2,l:3,gf:21,ga:16}, friendly: {w:9,d:3,l:12,gf:45,ga:56} },
  'Germany|Sweden': { comp: {w:7,d:2,l:3,gf:27,ga:15}, friendly: {w:8,d:5,l:5,gf:33,ga:26} },
  'Germany|Switzerland': { comp: {w:4,d:2,l:2,gf:14,ga:10}, friendly: {w:5,d:4,l:4,gf:21,ga:21} },
  'Germany|Czechia': { comp: {w:5,d:2,l:2,gf:17,ga:10}, friendly: {w:3,d:1,l:1,gf:10,ga:7} },
  'Germany|Norway': { comp: {w:5,d:1,l:2,gf:18,ga:8}, friendly: {w:7,d:4,l:3,gf:28,ga:15} },
  'Germany|Scotland': { comp: {w:4,d:2,l:1,gf:14,ga:8}, friendly: {w:5,d:3,l:3,gf:21,ga:14} },
  'Germany|Bosnia and Herz.': { comp: {w:3,d:0,l:0,gf:11,ga:1}, friendly: {w:1,d:0,l:1,gf:3,ga:3} },
  'Germany|Turkey': { comp: {w:4,d:1,l:1,gf:14,ga:7}, friendly: {w:2,d:1,l:1,gf:6,ga:5} },
  'Germany|Croatia': { comp: {w:3,d:0,l:3,gf:10,ga:9}, friendly: {w:2,d:1,l:1,gf:9,ga:7} },
  'Netherlands|Belgium': { comp: {w:5,d:3,l:5,gf:22,ga:22}, friendly: {w:12,d:8,l:12,gf:55,ga:56} },
  'Netherlands|Spain': { comp: {w:3,d:2,l:7,gf:17,ga:25}, friendly: {w:5,d:4,l:5,gf:22,ga:21} },
  'Netherlands|France': { comp: {w:3,d:2,l:7,gf:10,ga:19}, friendly: {w:5,d:5,l:6,gf:20,ga:26} },
  'Netherlands|Austria': { comp: {w:4,d:0,l:0,gf:10,ga:2}, friendly: {w:3,d:0,l:1,gf:7,ga:3} },
  'Netherlands|Portugal': { comp: {w:2,d:1,l:4,gf:8,ga:11}, friendly: {w:2,d:1,l:3,gf:7,ga:10} },
  'Netherlands|England': { comp: {w:2,d:3,l:3,gf:14,ga:16}, friendly: {w:4,d:6,l:3,gf:17,ga:16} },
  'Netherlands|Switzerland': { comp: {w:2,d:0,l:1,gf:5,ga:4}, friendly: {w:3,d:1,l:1,gf:9,ga:5} },
};

export function getH2H(teamA: string, teamB: string): H2HEntry | null {
  return H2H[`${teamA}|${teamB}`] ?? H2H[`${teamB}|${teamA}`] ?? null;
}
